# Generated by Django 2.0 on 2017-12-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='article',
            field=models.CharField(default='original', max_length=100),
        ),
    ]
